"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Lang = "zh" | "en";

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

// 翻譯字典
const translations: Record<Lang, Record<string, string>> = {
  zh: {
    // Header Nav
    "nav.home": "首頁",
    "nav.services": "服務項目",
    "nav.portfolio": "參與作品集",
    "nav.team": "團隊成員",
    "nav.about": "關於我們",
    "nav.contact": "聯絡我們",

    // Hero Carousel
    "hero.learnMore": "了解更多",
    "hero.contactUs": "合作洽詢",
    "hero.production": "參與製作",

    // Hero Slides
    "slide1.title": "《百萬人推理》",
    "slide1.subtitle": "Netflix 原創影集",
    "slide1.category": "現場檔案管理 / Netflix IMF 封包製作",
    "slide2.title": "《雙囍》",
    "slide2.subtitle": "院線電影",
    "slide2.category": "現場檔案管理 / 後期影像全流程 / DCP 製作",
    "slide3.title": "《功夫》",
    "slide3.subtitle": "院線電影",
    "slide3.category": "現場檔案管理 / 後期影像全流程",
    "slide4.title": "《陽光女子合唱團》",
    "slide4.subtitle": "院線電影",
    "slide4.category": "現場檔案管理 / 後期影像全流程規劃",
    "slide5.title": "《大濛》",
    "slide5.subtitle": "院線電影",
    "slide5.category": "現場檔案管理 / 影音同步 / ONLINE EDITING",
    "slide6.title": "《凶宅專賣店》",
    "slide6.subtitle": "Disney+",
    "slide6.category": "現場檔案管理 / 後期影像全流程",
    "slide39.title": "《乩身》",
    "slide39.subtitle": "Netflix 原創影集",
    "slide39.category": "現場檔案管理 / HDR 後期影像全流程 / Netflix HDR IMF 封包製作",

    // Latest Section
"latest.sectionLabel": "Latest Release",
                "latest.sectionTitle": "最新上映",
    "latest.viewAll": "查看全部作品",

    // Projects
    "project1.title": "《百萬人推理》",
    "project1.category": "Netflix 原創影集",
    "project1.services": "現場檔案管理 / Netflix IMF 封包製作",
    "project2.title": "《雙囍》",
    "project2.category": "院線電影",
    "project2.services": "現場檔案管理 / 後期影像全流程 / DCP 封包製作",
    "project3.title": "《功夫》",
    "project3.category": "院線電影",
    "project3.services": "後期檔案管理 / 後期影像全流程",
    "project4.title": "《陽光女子合唱團》",
    "project4.category": "院線電影",
    "project4.services": "現場檔案管理 / 後期影像全流程規劃",
    "project5.title": "《大濛》",
    "project5.category": "院線電影",
    "project5.services": "現場檔案管理 / 影音同步 / Online Editing",
    "project6.title": "《蟲》",
    "project6.category": "院線電影",
    "project6.services": "現場檔案管理 / 後期影像全流程 / DCP 封包製作",
    "project7.title": "《女孩》",
    "project7.category": "院線電影",
    "project7.services": "現場檔案管理 / 後期影像全流程 / DCP 封包製作",
    "project8.title": "《我們意外的勇氣》",
    "project8.category": "院線電影",
    "project8.services": "現場檔案管理 / 影音同步工程",
    "project9.title": "《泥娃娃》",
    "project9.category": "院線電影",
    "project9.services": "現場檔案管理 / 後期影像全流程 / DCP 封包製作",
    "project10.title": "《我家的事》",
    "project10.category": "院線電影",
    "project10.services": "現場檔案管理 / 影音同步工程",
    "project11.title": "《有病才會喜歡你》",
    "project11.category": "院線電影",
    "project11.services": "現場檔案管理 / 影音同步工程 / 後期套片工程",
    "project12.title": "《監所男子囚生記》",
    "project12.category": "愛奇藝 iQIYI 影集",
    "project12.services": "現場檔案管理 / 後期影像全流程 / iQIYI IMF 封包製作",
    "project13.title": "《我與惡的距離2》",
    "project13.category": "公共電視 PTS 影集",
    "project13.services": "現場檔案管理 / 影音同步工程",
    "project14.title": "《忘了我記得》",
    "project14.category": "Netflix 原創影集",
    "project14.services": "現場檔案管理 / HDR 後期影像全流程 / Netflix HDR IMF 封包製作",
    "project15.title": "《凶宅專賣店》",
    "project15.category": "Disney+",
    "project15.services": "現場檔案管理 / 後期影像全流程",
    "project16.title": "《壞男孩》",
    "project16.category": "電影",
    "project16.services": "後期檔案管理 / 影音同步工程",
    "project17.title": "《還錢》",
    "project17.category": "電影",
    "project17.services": "現場檔案管理 / 影音同步工程 / Online Editing",
    "project18.title": "《何百芮的地獄毒白》",
    "project18.category": "HBO GO",
    "project18.services": "後期檔案管理 / 後期影像全流程",
    "project19.title": "《青春18×2 通往有你的旅程》",
    "project19.category": "電影",
    "project19.services": "現場檔案管理 / 後期影像全流程",
    "project20.title": "《莎莉》",
    "project20.category": "電影",
    "project20.services": "現場檔案管理 / 影音同步工程",
    "project21.title": "《不夠善良的我們》",
    "project21.category": "公共電視 PTS 影集",
    "project21.services": "後期檔案管理 / 影音同步工程",
    "project22.title": "《鬼才之道》",
    "project22.category": "電影",
    "project22.services": "現場檔案管理 / 後期影像全流程",
    "project23.title": "《正港分局》",
    "project23.category": "Netflix 原創影集",
    "project23.services": "後期檔案管理 / 後期影像全流程",
    "project24.title": "《今天一起為愛鼓掌》",
    "project24.category": "八大戲劇台 GTV",
    "project24.services": "後期檔案管理 / 後期影像全流程",
    "project25.title": "《小雁與吳愛麗》",
    "project25.category": "電影",
    "project25.services": "現場檔案管理 / 後期影像全流程 / DCP 封包製作",
    "project26.title": "《為我辦一場西式喪禮》",
    "project26.category": "電影",
    "project26.services": "現場檔案管理 / 後期影像全流程",
    "project27.title": "《影后》",
    "project27.category": "Netflix 原創影集",
    "project27.services": "後期檔案管理 / 後期影像全流程",
    "project28.title": "《周處除三害》",
    "project28.category": "電影",
    "project28.services": "後期檔案管理 / 後期影像全流程",
    "project29.title": "《黑的教育》",
    "project29.category": "電影",
    "project29.services": "後期檔案管理 / 影音同步工程",
    "project30.title": "《疫起》",
    "project30.category": "電影",
    "project30.services": "現場檔案管理 / 影音同步工程 / Online Editing",
    "project31.title": "《請問，還有哪裡需要加強》",
    "project31.category": "電影",
    "project31.services": "後期檔案管理 / 後期影像全流程",
    "project32.title": "《我的麻吉4個鬼》",
    "project32.category": "電影",
    "project32.services": "現場檔案管理 / 後期影像全流程",
    "project33.title": "《查無此心》",
    "project33.category": "電影",
    "project33.services": "現場檔案管理 / 影音同步工程",
    "project34.title": "《關於我和鬼變成家人的那件事》",
    "project34.category": "電影",
    "project34.services": "現場檔案管理 / 後期影像全流程",
    "project35.title": "《此時此刻》",
    "project35.category": "Netflix 原創影集",
    "project35.services": "現場檔案管理",
    "project36.title": "《美食無間》",
    "project36.category": "iQIYI / 三立都會台 (SET City)",
    "project36.services": "後期檔案管理 / 影音同步工程",
    "project37.title": "《不良執念清除師》",
    "project37.category": "iQIYI",
    "project37.services": "後期檔案管理 / 影音同步工程",
    "project38.title": "《模仿犯》",
    "project38.category": "Netflix 原創影集",
    "project38.services": "後期檔案管理 / 後期影像全流程 / Netflix IMF 封包製作",
    "project39.title": "《乩身》",
    "project39.category": "Netflix 原創影集",
    "project39.services": "現場檔案管理 / HDR 後期影像全流程 / Netflix HDR IMF 封包製作",

    // Services
    "service1.title": "現場檔案管理",
    "service1.titleEn": "On-Set Data Management",
    "service1.desc": "專業檔案管理團隊駐場服務，即時備份、素材畫面監看、檔案歸檔，確保每一格影像安全無虞。",
    "service2.title": "後期檔案管理",
    "service2.titleEn": "Post-Production Data Management",
    "service2.desc": "從拍攝素材到最終交付，完整的檔案流程管理與專業的影音技術整合、各種版本控管與跨部門協作無縫銜接。",
    "service3.title": "影音同步",
    "service3.titleEn": "Audio-Video Synchronization",
    "service3.desc": "高精度影音同步處理，針對不同剪輯軟體有不同的工作流程，加速後期製作流程，從現場收音到混音的完美對接。",
    "service4.title": "套片與特效出檔作業",
    "service4.titleEn": "Online Editing / Conforming",
    "service4.desc": "精確的套片作業，確保剪輯版本與原始攝影素材完美對應，呈現最高畫質成品，並與合作的特效團隊對接，確實把關每一個階段的色彩管理。",
    "service5.title": "DCP 製作",
    "service5.titleEn": "DCP Mastering",
    "service5.desc": "符合 DCI 規格的數位電影包製作，支援 2K/4K 規格，讓作品在大銀幕完美呈現。",
    "service6.title": "Netflix 規格製作",
    "service6.titleEn": "Netflix Specification Delivery",
    "service6.desc": "完全符合 Netflix 技術規格的母帶製作與交付，包含 IMF 封裝、HDR 調光、音頻規格認證，讓作品在 Netflix 平台完美呈現。",
    "service7.title": "SDR 與 HDR 調色製作",
    "service7.titleEn": "SDR & HDR Color Grading",
    "service7.desc": "專業的 SDR / HDR 雙版本調色製作，精準色彩管理與 ACES 工作流程，確保從 Rec.709 到 Rec.2020 / PQ / HLG 各種規格的完美呈現，滿足院線、串流平台與電視播出的不同需求。",

    // Services Page
    "servicesPage.label": "What We Do",
    "servicesPage.title": "服務項目",
    "servicesPage.desc": "從片場到銀幕，ECN2 STUDIO 提供全方位的專業影視後期技術服務。",

    // Portfolio Page
    "portfolioPage.label": "Portfolio",
    "portfolioPage.title": "參與作品集",
    "portfolioPage.desc": "探索我們參與過的影視製作專案。",

    // About Page
    "aboutPage.label": "About Us",
    "aboutPage.title": "關於我們",
    "aboutPage.desc": "認識 ECN2 STUDIO，一支專注於影視後期製作的專業團隊。",

    // About Section
    "about.p1": "ECN2 STUDIO 是一支在台灣專注於影視後期製作的專業團隊，從片場到銀幕，我們陪伴每一部作品走過最關鍵的旅程。",
    "about.p2": "我們深信，卓越的技術是講好故事的基石。無論是 Netflix 原創影集的規格要求，還是院線電影的 DCP 母帶製作，我們都以最高標準為每一個專案把關。",
    "about.p3": "從現場檔案管理到最終上映平台交付，ECN2 STUDIO 提供一站式的後期技術解決方案，讓創作者專注於創作，我們負責讓技術完美落地。",
                "about.value1.title": "精準交付",
                "about.value1.desc": "每一個檔案、每一格畫面，我們都以最嚴謹的標準把關，確保從片場到平台交付零失誤。",
                "about.value2.title": "跨部門整合",
                "about.value2.desc": "與拍攝現場製片端、攝影、調光、音效、特效等各部門緊密協作，確保每一個環節無縫銜接，高效推進專案進度。",
                "about.value3.title": "全流程把關",
                "about.value3.desc": "從現場檔案管理、後期製作到最終封裝交付，提供完整且無縫的技術支援。",
                "about.value4.title": "技術創新",
                "about.value4.desc": "持續導入最新的後期製作技術與工作流程，為每一部作品找到最佳的技術方案。",

    // Team Page
    "teamPage.label": "Our Team",
    "teamPage.title": "團隊成員",
    "teamPage.desc": "認識 ECN2 STUDIO 背後的專業團隊，每一位成員都是影視後期製作的專家。",

    // Team Members
    "team.m1.name": "成員一",
    "team.m1.role": "創辦人 / 技術總監",
    "team.m1.bio": "十年以上影視後期經驗，專精色彩管理與 HDR 工作流程，致力於為每部作品打造最佳技術方案。",
    "team.m2.name": "成員二",
    "team.m2.role": "後期製片",
    "team.m2.bio": "擅長跨部門溝通與專案排程管理，確保每一個環節準時交付，讓後期流程有條不紊地推進。",
    "team.m3.name": "成員三",
    "team.m3.role": "現場檔案管理師",
    "team.m3.bio": "片場第一線的檔案守護者，即時備份與素材管理是我的日常，零失誤是我對每個劇組的承諾。",
    "team.m4.name": "成員四",
    "team.m4.role": "現場檔案管理師",
    "team.m4.bio": "擁有豐富的現場拍攝經驗，熟悉各品牌攝影機格式與工作流程，為劇組提供最安心的保障。",
    "team.m5.name": "成員五",
    "team.m5.role": "影音同步工程師",
    "team.m5.bio": "精通各主流剪輯軟體的同步工作流程，從現場多軌收音到後期混音，每一格都精準對齊。",
    "team.m6.name": "成員六",
    "team.m6.role": "套片工程師",
    "team.m6.bio": "專注 Online Editing 與調光前置作業，確保剪輯版本與原始素材完美對應，呈現最高畫質。",
    "team.m7.name": "成員七",
    "team.m7.role": "調光師",
    "team.m7.bio": "以色彩說故事，熟悉 DaVinci Resolve 與 ACES 流程，打造每一幕的視覺情感與氛圍。",
    "team.m8.name": "成員八",
    "team.m8.role": "DCP / IMF 封包工程師",
    "team.m8.bio": "負責院線與串流平台的最終交付，精通 DCP、Netflix IMF、Disney+ 等各平台封裝規格。",
    "team.m9.name": "成員九",
    "team.m9.role": "後期技術工程師",
    "team.m9.bio": "對新技術充滿熱情，持續研究最前沿的後期工具與流程，為團隊帶來更高效的解決方案。",
    "team.m10.name": "成員十",
    "team.m10.role": "專案協調",
    "team.m10.bio": "細心且高效的專案管理者，負責串聯各環節的溝通協調，確保每個專案都能順利完成交付。",

    // Footer
    "footer.cta.label": "Get in Touch",
    "footer.cta.title": "準備好將您的故事變為現實了嗎？",
    "footer.cta.button": "聯絡我們",
    "footer.brandName": "伊西恩兔映像",
    "footer.slogan": "提供一站式的後期技術解決方案，讓創作者專注於創作，我們負責讓技術完美落地。",
    "footer.contact": "Contact",
  },
  en: {
    // Header Nav
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.portfolio": "Portfolio",
    "nav.team": "Team",
    "nav.about": "About",
    "nav.contact": "Contact",

    // Hero Carousel
    "hero.learnMore": "Learn More",
    "hero.contactUs": "Contact Us",
    "hero.production": "Production Services",

    // Hero Slides
    "slide1.title": "Million-Follower Detective",
    "slide1.subtitle": "Netflix Original Series",
    "slide1.category": "On-Set Data Mgmt / Netflix IMF Packaging",
    "slide2.title": "Double Happiness",
    "slide2.subtitle": "Theatrical Film",
    "slide2.category": "On-Set Data Mgmt / Full Post Pipeline / DCP",
    "slide3.title": "Kung Fu",
    "slide3.subtitle": "Theatrical Film",
    "slide3.category": "On-Set Data Mgmt / Full Post Pipeline",
    "slide4.title": "Sunshine Women's Choir",
    "slide4.subtitle": "Theatrical Film",
    "slide4.category": "On-Set Data Mgmt / Full Post Pipeline Planning",
    "slide5.title": "A Foggy Tale",
    "slide5.subtitle": "Theatrical Film",
    "slide5.category": "On-Set Data Mgmt / A/V Sync / Online Editing",
    "slide6.title": "Haunted House Secrets",
    "slide6.subtitle": "Disney+",
    "slide6.category": "On-Set Data Mgmt / Full Post Pipeline",
    "slide39.title": "Agent From Above",
    "slide39.subtitle": "Netflix Original Series",
    "slide39.category": "On-Set Data Mgmt / HDR Full Post Pipeline / Netflix HDR IMF Packaging",

    // Latest Section
    "latest.sectionLabel": "Latest Release",
    "latest.sectionTitle": "Latest Release",
    "latest.viewAll": "View All",

    // Projects
    "project1.title": "Million-Follower Detective",
    "project1.category": "Netflix Original Series",
    "project1.services": "On-Set Data Mgmt / Netflix IMF Packaging",
    "project2.title": "Double Happiness",
    "project2.category": "Theatrical Film",
    "project2.services": "On-Set Data Mgmt / Full Post Pipeline / DCP Mastering",
    "project3.title": "Kung Fu",
    "project3.category": "Theatrical Film",
    "project3.services": "Post-Production Data Management / Full Post-Production Pipeline",
    "project4.title": "Sunshine Women's Choir",
    "project4.category": "Theatrical Film",
    "project4.services": "On-Set Data Mgmt / Full Post Pipeline Planning",
    "project5.title": "A Foggy Tale",
    "project5.category": "Theatrical Film",
    "project5.services": "On-Set Data Mgmt / A/V Sync / Online Editing",
    "project6.title": "Locust",
    "project6.category": "Theatrical Film",
    "project6.services": "On-Set Data Mgmt / Full Post Pipeline / DCP Mastering",
    "project7.title": "Girl",
    "project7.category": "Theatrical Film",
    "project7.services": "On-Set Data Mgmt / Full Post Pipeline / DCP Mastering",
    "project8.title": "Unexpected Courage",
    "project8.category": "Theatrical Film",
    "project8.services": "On-Set Data Mgmt / A/V Sync",
    "project9.title": "Mudborn",
    "project9.category": "Theatrical Film",
    "project9.services": "On-Set Data Mgmt / Full Post Pipeline / DCP Mastering",
    "project10.title": "Family Matters",
    "project10.category": "Theatrical Film",
    "project10.services": "On-Set Data Mgmt / A/V Sync",
    "project11.title": "Lovesick",
    "project11.category": "Theatrical Film",
    "project11.services": "On-Set Data Mgmt / A/V Sync / Online Conforming",
    "project12.title": "OOPS! I'M IN JAIL",
    "project12.category": "iQIYI Series",
    "project12.services": "On-Set Data Mgmt / Full Post Pipeline / iQIYI IMF Packaging",
    "project13.title": "The World Between Us: After the Flames",
    "project13.category": "PTS (Taiwan Public Television) Series",
    "project13.services": "On-Set Data Mgmt / A/V Sync",
    "project14.title": "Forget You Not",
    "project14.category": "Netflix Original Series",
    "project14.services": "On-Set Data Mgmt / HDR Full Post Pipeline / Netflix HDR IMF Packaging",
    "project15.title": "Haunted House Secrets",
    "project15.category": "Disney+",
    "project15.services": "On-Set Data Mgmt / Full Post Pipeline",
    "project16.title": "The Young Hoodlum",
    "project16.category": "Theatrical Film",
    "project16.services": "Post-Production Data Mgmt / A/V Sync",
    "project17.title": "Breaking and Re-entering",
    "project17.category": "Theatrical Film",
    "project17.services": "On-Set Data Mgmt / A/V Sync / Online Editing",
    "project18.title": "The Accidental Influencer",
    "project18.category": "HBO GO",
    "project18.services": "Post-Production Data Mgmt / Full Post Pipeline",
    "project19.title": "18×2 Beyond Youthful Days",
    "project19.category": "Theatrical Film",
    "project19.services": "On-Set Data Mgmt / Full Post Pipeline",
    "project20.title": "Salli",
    "project20.category": "Theatrical Film",
    "project20.services": "On-Set Data Mgmt / A/V Sync",
    "project21.title": "Imperfect Us",
    "project21.category": "PTS (Taiwan Public Television) Series",
    "project21.services": "Post-Production Data Mgmt / A/V Sync",
    "project22.title": "Dead Talents Society",
    "project22.category": "Theatrical Film",
    "project22.services": "On-Set Data Mgmt / Full Post Pipeline",
    "project23.title": "GG Precinct",
    "project23.category": "Netflix Original Series",
    "project23.services": "Post-Production Data Mgmt / Full Post Pipeline",
    "project24.title": "Us Without Sex",
    "project24.category": "GTV Drama Series",
    "project24.services": "Post-Production Data Mgmt / Full Post Pipeline",
    "project25.title": "Yen and Ai-Lee",
    "project25.category": "Theatrical Film",
    "project25.services": "On-Set Data Mgmt / Full Post Pipeline / DCP Mastering",
    "project26.title": "See You",
    "project26.category": "Theatrical Film",
    "project26.services": "On-Set Data Mgmt / Full Post Pipeline",
    "project27.title": "Born for the Spotlight",
    "project27.category": "Netflix Original Series",
    "project27.services": "Post-Production Data Mgmt / Full Post Pipeline",
    "project28.title": "The Pig, the Snake and the Pigeon",
    "project28.category": "Theatrical Film",
    "project28.services": "Post-Production Data Mgmt / Full Post Pipeline",
    "project29.title": "Bad Education",
    "project29.category": "Theatrical Film",
    "project29.services": "Post-Production Data Mgmt / A/V Sync",
    "project30.title": "Eye of the Storm",
    "project30.category": "Theatrical Film",
    "project30.services": "On-Set Data Mgmt / A/V Sync / Online Editing",
    "project31.title": "Miss Shampoo",
    "project31.category": "Theatrical Film",
    "project31.services": "Post-Production Data Mgmt / Full Post Pipeline",
    "project32.title": "Hello Ghost",
    "project32.category": "Theatrical Film",
    "project32.services": "On-Set Data Mgmt / Full Post Pipeline",
    "project33.title": "The Abandoned",
    "project33.category": "Theatrical Film",
    "project33.services": "On-Set Data Mgmt / A/V Sync",
    "project34.title": "Marry My Dead Body",
    "project34.category": "Theatrical Film",
    "project34.services": "On-Set Data Mgmt / Full Post Pipeline",
    "project35.title": "At the Moment",
    "project35.category": "Netflix Original Series",
    "project35.services": "On-Set Data Management",
    "project36.title": "Gourmet Affairs",
    "project36.category": "iQIYI / SET City",
    "project36.services": "Post-Production Data Mgmt / A/V Sync",
    "project37.title": "Oh No! Here Comes Trouble",
    "project37.category": "iQIYI",
    "project37.services": "Post-Production Data Mgmt / A/V Sync",
    "project38.title": "Copycat Killer",
    "project38.category": "Netflix Original Series",
    "project38.services": "Post-Production Data Mgmt / Full Post Pipeline / Netflix IMF Packaging",
    "project39.title": "Agent From Above",
    "project39.category": "Netflix Original Series",
    "project39.services": "On-Set Data Mgmt / HDR Full Post Pipeline / Netflix HDR IMF Packaging",

    // Services
    "service1.title": "On-Set Data Management",
    "service1.titleEn": "On-Set Data Management",
    "service1.desc": "Professional DIT team on-set services, including real-time backup, color monitoring, and file archiving to ensure every frame is safe.",
    "service2.title": "Post-Production Data Management",
    "service2.titleEn": "Post-Production Data Management",
    "service2.desc": "Complete file workflow management from raw footage to final delivery, with version control and seamless cross-department collaboration.",
    "service3.title": "Audio-Video Synchronization",
    "service3.titleEn": "Audio-Video Synchronization",
    "service3.desc": "High-precision audio-video sync processing, supporting multi-camera and multi-track workflows, from on-set sound to final mix.",
    "service4.title": "Online Editing / Conforming",
    "service4.titleEn": "Online Editing / Conforming",
    "service4.desc": "Precise conforming to ensure the edited version perfectly matches the original camera footage, delivering the highest quality output.",
    "service5.title": "DCP Mastering",
    "service5.titleEn": "DCP Mastering",
    "service5.desc": "DCI-compliant Digital Cinema Package production, supporting 2K/4K and Dolby Atmos for perfect theatrical presentation.",
    "service6.title": "Netflix Specification Delivery",
    "service6.titleEn": "Netflix Specification Delivery",
    "service6.desc": "Full compliance with Netflix technical specifications, including IMF packaging, HDR grading, and audio specification certification.",
    "service7.title": "SDR & HDR Color Grading",
    "service7.titleEn": "SDR & HDR Color Grading",
    "service7.desc": "Professional dual-version SDR/HDR color grading with precise color management and ACES workflow, ensuring flawless delivery across Rec.709, Rec.2020, PQ, and HLG specifications for theatrical, streaming, and broadcast requirements.",

    // Services Page
    "servicesPage.label": "What We Do",
    "servicesPage.title": "Services",
    "servicesPage.desc": "From set to screen, ECN2 STUDIO provides comprehensive professional post-production services.",

    // Portfolio Page
    "portfolioPage.label": "Portfolio",
    "portfolioPage.title": "Portfolio",
    "portfolioPage.desc": "Explore our film and television production projects.",

    // About Page
    "aboutPage.label": "About Us",
    "aboutPage.title": "About Us",
    "aboutPage.desc": "Meet ECN2 STUDIO, a professional team dedicated to post-production excellence.",

    // About Section
    "about.p1": "ECN2 STUDIO is a professional team based in Taiwan, specializing in film and television post-production. From set to screen, we accompany every project through its most critical journey.",
    "about.p2": "We believe that technical excellence is the foundation of great storytelling. Whether it's the strict specifications of a Netflix original series or DCP mastering for theatrical release, we hold every project to the highest standards.",
    "about.p3": "From on-set data management to final platform delivery, ECN2 STUDIO provides one-stop post-production technical solutions, allowing creators to focus on their art while we ensure flawless technical execution.",
                "about.value1.title": "Precise Delivery",
                "about.value1.desc": "Every file, every frame — we uphold the strictest standards to ensure zero errors from set to platform delivery.",
                "about.value2.title": "Cross-Department Integration",
                "about.value2.desc": "Working closely with on-set production teams, cinematographers, colorists, sound designers, and VFX teams to ensure seamless coordination and efficient project progress.",
                "about.value3.title": "Full Pipeline QC",
                "about.value3.desc": "From on-set data management to post-production and final packaging, we provide seamless end-to-end technical support.",
                "about.value4.title": "Technical Innovation",
                "about.value4.desc": "Continuously adopting the latest post-production technologies and workflows to find the best technical solution for every project.",

    // Team Page
    "teamPage.label": "Our Team",
    "teamPage.title": "Our Team",
    "teamPage.desc": "Meet the professionals behind ECN2 STUDIO — every member is an expert in film & TV post-production.",

    // Team Members
    "team.m1.name": "Member 1",
    "team.m1.role": "Founder / Technical Director",
    "team.m1.bio": "Over a decade of post-production experience, specializing in color management and HDR workflows, dedicated to delivering the best technical solutions.",
    "team.m2.name": "Member 2",
    "team.m2.role": "Post-Production Producer",
    "team.m2.bio": "Expert in cross-department communication and project scheduling, ensuring every milestone is met and workflows run smoothly.",
    "team.m3.name": "Member 3",
    "team.m3.role": "On-Set DIT",
    "team.m3.bio": "The frontline guardian of on-set data — real-time backup and media management are my daily routine, with zero errors as my promise.",
    "team.m4.name": "Member 4",
    "team.m4.role": "On-Set DIT",
    "team.m4.bio": "Rich on-set experience with expertise in various camera formats and workflows, providing crews with reliable data management support.",
    "team.m5.name": "Member 5",
    "team.m5.role": "A/V Sync Engineer",
    "team.m5.bio": "Proficient in sync workflows across major editing platforms, from multi-track field recording to final mix — every frame precisely aligned.",
    "team.m6.name": "Member 6",
    "team.m6.role": "Online Editor",
    "team.m6.bio": "Focused on online editing and pre-grade preparation, ensuring editorial conforms perfectly match original footage for the highest quality output.",
    "team.m7.name": "Member 7",
    "team.m7.role": "Colorist",
    "team.m7.bio": "Telling stories through color, proficient in DaVinci Resolve and ACES workflows, crafting the visual emotion and atmosphere of every scene.",
    "team.m8.name": "Member 8",
    "team.m8.role": "DCP / IMF Packaging Engineer",
    "team.m8.bio": "Responsible for final delivery to theaters and streaming platforms, specializing in DCP, Netflix IMF, Disney+ and other packaging specifications.",
    "team.m9.name": "Member 9",
    "team.m9.role": "Post-Production Technical Engineer",
    "team.m9.bio": "Passionate about new technologies, continuously researching cutting-edge post-production tools and workflows for more efficient solutions.",
    "team.m10.name": "Member 10",
    "team.m10.role": "Project Coordinator",
    "team.m10.bio": "A detail-oriented and efficient project coordinator, bridging communication across all departments to ensure smooth and timely delivery.",

    // Footer
    "footer.cta.label": "Get in Touch",
    "footer.cta.title": "Ready to bring your story to life?",
    "footer.cta.button": "Contact Us",
    "footer.brandName": "伊西恩兔映像",
    "footer.slogan": "One-stop post-production solutions — so creators can focus on creating, while we ensure flawless technical execution.",
    "footer.contact": "Contact",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("zh");

  // 從 localStorage 讀取語言設定
  useEffect(() => {
    const saved = localStorage.getItem("lang") as Lang | null;
    if (saved === "en" || saved === "zh") {
      setLangState(saved);
    }
  }, []);

  // 切換語言時同時存入 localStorage
  const setLang = (newLang: Lang) => {
    setLangState(newLang);
    localStorage.setItem("lang", newLang);
  };

  const t = (key: string): string => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

